Refacto du code
WildCodeSchool/lyon-js-sept-2020-g2 pull request #74
Opened 2020-11-15 15:19 UTC by nicolasdantas

Composants News, DataByCounty et TopFive modifiés en composants fonctionnels.
Création d'un contexte afin d'éviter des appels à l'API inutiles.

2020-11-16 11:14 UTC, ComicScrip requested changes
Top d'avoir réusiné, attention cependant, je crois qu'on a une regression : 
Je vais sur le site, je sélectionne un département dans le select et j'essaie de cliquer sur un autre département sur la map et là ça ne fonctionne pas. 
Si je recharge la page et que je passe direct par la carte sans renseigner le select, ça fonctionne

2020-11-16 16:41 UTC, nicolasdantas commented
Bug fixé ! 
On a refacto l'ensemble pour créer un deuxième contexte contenant les données du département sélectionné.

2020-11-16 17:11 UTC, ComicScrip requested changes

2020-11-16 17:11 UTC, ComicScrip commented on src/components/Map.js
> +  const allDataDep = allData
Petit bug ici : 
Quand je sélectionne un critère pour coloriser la carte, la console pète des erreurs dans tous les sens car les dépendances du useEffect ne sont pas "stables". En effet, allDataDep est un tableau qui est recréé à chaque render. Donc dès que le composant fait son rendu, la dep change, le useEffect se re-déclanche, et met à jour un état, donc le composant se re-rend et ainsi de suite. 

Pour régler le pb il suffit mettre allDataDep dans un useMemo, un peu comme ça :
```js
const allDataDep = useMemo(() => allData.filter(...).map(...), [allData]);
```

2020-11-16 18:18 UTC, nicolasdantas commented on src/components/Map.js
> +  const allDataDep = allData
Bug fixé :+1:

2020-11-17 13:12 UTC, ComicScrip commented on src/components/Map.js
> +  const allDataDep = allData
Top notch !

2020-11-17 13:13 UTC, merged