ajout du loader pendant le chargement de la page
WildCodeSchool/lyon-js-sept-2020-g2 pull request #82
Opened 2020-11-24 11:15 UTC by LouiseCeccaldi

Le code a été rajouté dans les fichiers: 
index.html (dans le body et dans le head pour le style)
App.js

2020-11-24 17:11 UTC, nicolasdantas commented
Il y a un warning dans la console, il faut rajouter isLoading en dépendance du useEffect (et enlever le code commenté :) )

2020-11-25 12:09 UTC, ComicScrip requested changes

2020-11-25 12:09 UTC, ComicScrip commented on src/App.js
> +  function fakeRequest() {
Pourquoi avoir mis un loader sur un chargement "fake" ??

2020-11-25 12:09 UTC, ComicScrip commented on public/index.html
> +      .loader-container {
Pourquoi définir le style ici et pas dans un fichier à part comme c'est le cas pour le reste de l'application ?

2020-11-25 13:30 UTC, LouiseCeccaldi commented
corrections faites.

2020-11-25 15:30 UTC, merged